services:
  runner:
    container_name: gh-runner
    # image: ghcr.io/jamesonrgrieve-instruction/runner:main
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ../../.env
    environment:
      - REPO=<owner>/<repo>
      - TOKEN=${GH_ACTIONS_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    network_mode: bridge
