services:
  runner:
    env_file:
      - ../../.env
    container_name: gh-runner
    # image: ghcr.io/jamesonrgrieve-instruction/runner:main
    build:
      context: .
      dockerfile: Dockerfile
    restart: always

    environment:
      # REPO is required when using GH_USER_NAME
      - GH_REPO=${GH_REPO:-}
      - GH_ACTIONS_TOKEN=${GH_ACTIONS_TOKEN}
      - GH_ORG_NAME=${GH_ORG_NAME:-}
      - GH_USER_NAME=${GH_USER_NAME:-}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    network_mode: bridge
