services:
  runner:
    container_name: gh-runner
    # image: ghcr.io/jamesonrgrieve-instruction/runner:main
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      # Set either ORG_NAME or USER_NAME, not both
      # - ORG_NAME=your-organization
      # - USER_NAME=your-username
      # REPO is required when using USER_NAME
      - REPO=${GH_REPO:-}
      - TOKEN=${GH_ACTIONS_TOKEN}
      - ORG_NAME=${GH_ORG_NAME:-}
      - USER_NAME=${GH_USER_NAME:-}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    network_mode: bridge
